<a href="https://colab.research.google.com/github/imekss/phyton_analytics_demo/blob/main/code_examples_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [2]:
x = 5

In [ ]:
np.int8

In [23]:
a = np.array([1,2,3,4], dtype=np.int8)

In [13]:
b = np.array([5,6.7,7,8])

In [ ]:
b[2]

In [24]:
a.dtype

dtype('int8')

In [ ]:
b.dtype

In [ ]:
a[2:]

**Dimesions and shapes**

In [25]:
a = np.array([
              [1,2,3],
              [4,5,6]
])

In [26]:
a.shape

(2, 3)

**Boolean arrays**

In [27]:
a = np.arange(5)

In [28]:
a

array([0, 1, 2, 3, 4])

In [29]:
a >= 2

array([False, False,  True,  True,  True])

In [30]:
a[a >= 2]

array([2, 3, 4])

In [32]:
a.mean()

2.0